#!/bin/sh 

: ${HOST_OS:=unknown}

fail() { printf "\n\033[01;31mERROR: $*\033[00m\n" ; exit 1 ; }

_FindOs() {
	#Ubuntu
	if grep -q Ubuntu /etc/issue 2> /dev/null ; then
		HOST_OS=ubuntu
		return;
	fi
	#Fedora
	if grep -q Fedora /etc/issue 2> /dev/null ; then
		HOST_OS=fedora
		return;
	fi
	#CentOS
	if grep -q CentOS /etc/issue 2> /dev/null ; then
		HOST_OS=centos
		return;
	fi
}

_InstallRpm() {
	#check root
	[ `id -u` -eq 0 ] || fail "I cannot continue, you should be root or run it with sudo!"

	#first key
	rpm --import http://safrm.net/repo/rpm/safrmnet.key || fail "failed to add repo key"
	#add repo
	REPO_FILE=/etc/yum.repos.d/safrm_net.repo
	if [ ! -e $REPO_FILE ]; then
		 wget -N http://safrm.net/repo/safrm_net.repo -O $REPO_FILE || fail "failed to download repo file" 
	fi

	#enable EPEL
	yum install epel-release -y || fail "to enable EPEL"
}

_InstallDeb() {
	#check root
	[ `id -u` -eq 0 ] || fail "I cannot continue, you should be root or run it with sudo!"
	#first key
	wget -N -O - http://safrm.net/releases/safrmnet.key | sudo apt-key add - || fail "failed to add repo key"
	#add repo
	REPO_FILE=/etc/apt/sources.list.d/safrm_net.list
	if [ ! -e $REPO_FILE ]; then
		wget -N http://safrm.net/repo/safrm_net.list -O $REPO_FILE || fail "failed to download repo file" 
	fi

	#update index
	sudo apt-get update
}


_FindOs
echo "HOST_OS=$HOST_OS"

case $HOST_OS in
  fedora|centos)  _InstallRpm ;;
  ubuntu)  _InstallDeb ;;
  unknown|*)
	 fail "Unknown system: $HOST_OS"
esac





